spring:
  mail:
    host: smtp.gmail.com
    port: 587
    # username: dungthemai20@gmail.com
    # password: tsotbcciabtdafqa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true
