spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: htlxh1@gmail.com
    password: lllxtqyelplzuzcn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true
